# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: produk-service
spec:
  # Selector: HARUS cocok dengan label di 'pod.yaml'
  selector:
    app: produk-service
  
  # Type: NodePort memungkinkan akses dari host Docker Desktop Anda
  type: NodePort
  
  ports:
    - protocol: TCP
      port: 80          # Port yang diekspos oleh Service
      targetPort: 8081    # Port aplikasi di dalam Pod (containerPort)